version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.4.0

    steps:
      - checkout

      - run: cd puppeteer-jest && npm install
      - run: cd puppeteer-jest && npm run test
