version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
       - image: circleci/node:12.4.0
    steps:
      - checkout
      - run: cd puppeteer-jest && npm install
      - run: cd puppeteer-jest && npm run test
