version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0
    working_directory: puppeteer-jest
    steps:
      - checkout
      - run: npm install
      - run: npm run test
