version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd puppeteer-percy-jest && npm install
            - run: cd puppeteer-percy-jest && npm run test:math
workflows:
  build-and-test:
    jobs:
      - build-and-test
